---
kind: pipeline
type: docker
name: default

steps:
- name: Test
  image: python:3.8.0-buster
  commands:
  - pip3 install .
  - pytest tests/test.py
  environment:
    REDIS_HOST: cache
  
services:
- name: cache
  image: redis